development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: parlamento
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: parlamento_fast
  pool: 5
  username: root
  password: root
